# Workflow designed to publish the API & Client to dockerhub
name: Publish to Dockerhub
on:
  push:
    branches: [ main ]
env:
  DOCKERHUB_USERNAME: stuartaharrison
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $env.DOCKERHUB_USERNAME/unstable-unicorns-api:latest
